/**
 * Prompt loader - AUTO-GENERATED FILE
 *
 * This file is automatically generated by scripts/generate-prompt-loader.js
 * Do not edit this file directly - your changes will be overwritten.
 *
 * All prompt implementations that use the @Prompt decorator are automatically imported here.
 */

// Auto-generated imports
import '../prompts/analysis/code-performance-prompt';
import '../prompts/analysis/code-security-prompt';
import '../prompts/analysis/code-smell-prompt';
import '../prompts/analysis/test-mcp-tools-prompt';
import '../prompts/documentation/class-diagram-prompt';
import '../prompts/documentation/flowchart-prompt';

// No need to export anything - the imports themselves will register the prompts
