/**
 * Resource loader - AUTO-GENERATED FILE
 *
 * This file is automatically generated by scripts/generate-resource-loader.js
 * Do not edit this file directly - your changes will be overwritten.
 *
 * All resource implementations that use the @Resource decorator are automatically imported here.
 */

// Auto-generated imports
import '../resources/mcp-log/index';

// No need to export anything - the imports themselves will register the resources
