/**
 * Tool loader - AUTO-GENERATED FILE
 *
 * This file is automatically generated by scripts/generate-tool-loader.js
 * Do not edit this file directly - your changes will be overwritten.
 *
 * Tools are organized by category for selective loading to improve startup time.
 * Heavy SDKs are only loaded when their category is actually used.
 */

import { logWarn, logError } from '../services/logger';

/**
 * Map of category names to their loader functions.
 * Each loader function dynamically imports all tools in that category.
 */
export const categoryLoaders: Record<string, () => Promise<void>> = {
  'CrUX': async () => {
    await import('../tools/crux/index');
  },
  'Github: Actions': async () => {
    await import('../tools/github/actions/cancel-workflow-run-tool');
    await import('../tools/github/actions/create-dispatch-tool');
    await import('../tools/github/actions/get-workflow-run-job-tool');
    await import('../tools/github/actions/get-workflow-run-logs-tool');
    await import('../tools/github/actions/get-workflow-run-tool');
    await import('../tools/github/actions/get-workflow-tool');
    await import('../tools/github/actions/list-workflow-run-jobs-tool');
    await import('../tools/github/actions/list-workflow-runs-tool');
    await import('../tools/github/actions/list-workflows-tool');
    await import('../tools/github/actions/rerun-workflow-tool');
  },
  'Github: Branches': async () => {
    await import('../tools/github/branches/get-branch-tool');
    await import('../tools/github/branches/github-create-branch-tool');
    await import('../tools/github/branches/github-create-update-file-content-tool');
    await import('../tools/github/branches/list-branches-tool');
    await import('../tools/github/branches/merge-branch-tool');
    await import('../tools/github/branches/rename-branch-tool');
  },
  'Github: Dependabot': async () => {
    await import('../tools/github/dependabot/get-dependabot-alert-tool');
    await import('../tools/github/dependabot/list-dependabot-alerts-tool');
    await import('../tools/github/dependabot/update-dependabot-alert-tool');
  },
  'Github: Discussions': async () => {
    await import('../tools/github/discussions/delete-commit-comment-reaction-tool');
    await import('../tools/github/discussions/delete-issue-comment-reaction-tool');
    await import('../tools/github/discussions/delete-issue-reaction-tool');
    await import('../tools/github/discussions/delete-pull-request-comment-reaction-tool');
    await import('../tools/github/discussions/delete-release-reaction-tool');
  },
  'Github: Gists': async () => {
    await import('../tools/github/gists/create-gist-tool');
    await import('../tools/github/gists/delete-gist-tool');
    await import('../tools/github/gists/get-gist-tool');
    await import('../tools/github/gists/list-gists-tool');
    await import('../tools/github/gists/update-gist-tool');
  },
  'Github: Issues': async () => {
    await import('../tools/github/issues/add-issue-comment-tool');
    await import('../tools/github/issues/add-sub-issue-tool');
    await import('../tools/github/issues/create-issue-tool');
    await import('../tools/github/issues/get-issue-comments-tool');
    await import('../tools/github/issues/get-tool');
    await import('../tools/github/issues/list-issues-tool');
    await import('../tools/github/issues/list-sub-issues-tool');
    await import('../tools/github/issues/remove-sub-issue-tool');
    await import('../tools/github/issues/update-issue-tool');
    await import('../tools/github/search/search-issues-tool');
  },
  'Github: Orgs': async () => {
    await import('../tools/github/org/get-org-tool');
    await import('../tools/github/org/list-my-orgs-tool');
    await import('../tools/github/org/list-orgs-tool');
  },
  'Github: Projects': async () => {
    await import('../tools/github/projects/add-project-draft-issue-tool');
    await import('../tools/github/projects/add-project-item-tool');
    await import('../tools/github/projects/archive-project-item-tool');
    await import('../tools/github/projects/clear-project-item-field-tool');
    await import('../tools/github/projects/convert-draft-to-issue-tool');
    await import('../tools/github/projects/create-project-field-tool');
    await import('../tools/github/projects/create-project-tool');
    await import('../tools/github/projects/delete-project-field-tool');
    await import('../tools/github/projects/delete-project-item-tool');
    await import('../tools/github/projects/get-project-tool');
    await import('../tools/github/projects/list-project-fields-tool');
    await import('../tools/github/projects/list-project-items-tool');
    await import('../tools/github/projects/list-projects-tool');
    await import('../tools/github/projects/unarchive-project-item-tool');
    await import('../tools/github/projects/update-project-draft-issue-tool');
    await import('../tools/github/projects/update-project-field-tool');
    await import('../tools/github/projects/update-project-item-field-tool');
    await import('../tools/github/projects/update-project-item-position-tool');
    await import('../tools/github/projects/update-project-tool');
  },
  'Github: Pulls': async () => {
    await import('../tools/github/pull-requests/add-reviewers-tool');
    await import('../tools/github/pull-requests/create-pull-request-review-tool');
    await import('../tools/github/pull-requests/create-pull-request-tool');
    await import('../tools/github/pull-requests/get-pr-review-threads-tool');
    await import('../tools/github/pull-requests/get-pull-request-comments-tool');
    await import('../tools/github/pull-requests/get-pull-request-files-tool');
    await import('../tools/github/pull-requests/get-pull-request-reviews-tool');
    await import('../tools/github/pull-requests/get-pull-request-status-tool');
    await import('../tools/github/pull-requests/get-pull-request-tool');
    await import('../tools/github/pull-requests/list-pull-requests-tool');
    await import('../tools/github/pull-requests/mark-pull-request-ready-tool');
    await import('../tools/github/pull-requests/merge-pull-request-tool');
    await import('../tools/github/pull-requests/remove-reviewers-tool');
    await import('../tools/github/pull-requests/set-pr-review-thread-resolution-tool');
    await import('../tools/github/pull-requests/update-pull-request-branch-tool');
  },
  'Github: Releases': async () => {
    await import('../tools/github/releases/get-latest-release-tool');
    await import('../tools/github/releases/list-releases-tool');
  },
  'Github: Repos': async () => {
    await import('../tools/github/repos/get-content-tool');
    await import('../tools/github/repos/get-repository-tool');
    await import('../tools/github/repos/list-repos-tool');
    await import('../tools/github/repos/list-user-repos-tool');
    await import('../tools/github/repos/repository-topics-get-tool');
    await import('../tools/github/repos/repository-topics-update-tool');
  },
  'Github: Search': async () => {
    await import('../tools/github/search/search-code-tool');
    await import('../tools/github/search/search-commits-tool');
    await import('../tools/github/search/search-repos-tool');
  },
  'Github: Wiki': async () => {
    await import('../tools/github/wiki/index');
  },
  'Knowledge Graph': async () => {
    await import('../tools/knowledge-graph/add-observations-tool');
    await import('../tools/knowledge-graph/create-entities-tool');
    await import('../tools/knowledge-graph/create-relations-tool');
    await import('../tools/knowledge-graph/delete-entities-tool');
    await import('../tools/knowledge-graph/delete-observations-tool');
    await import('../tools/knowledge-graph/delete-relations-tool');
    await import('../tools/knowledge-graph/open-nodes-tool');
    await import('../tools/knowledge-graph/read-graph-tool');
    await import('../tools/knowledge-graph/search-nodes-tool');
  },
  'NPM': async () => {
    await import('../tools/npm/build-order-tool');
    await import('../tools/npm/dag-tool');
    await import('../tools/npm/doctor-tool');
    await import('../tools/npm/list-tool');
    await import('../tools/npm/tree-tool');
  },
  'PostgreSQL': async () => {
    await import('../tools/postgresql/index');
  },
  'Swagger': async () => {
    await import('../tools/swagger-hub/open-api-client-generator-tool/index');
    await import('../tools/swagger-hub/save-swagger-doc-tool/index');
  },
  'Utility': async () => {
    await import('../tools/claude-code-usage/index');
    await import('../tools/clipboard/index');
    await import('../tools/location-to-coords/index');
    await import('../tools/platform-session/logout-tool');
    await import('../tools/platform-session/reauth-tool');
    await import('../tools/tasks/index');
    await import('../tools/time/index');
    await import('../tools/utility/doctor-tool');
    await import('../tools/weather/index');
  },
  'k6': async () => {
    await import('../tools/k6/index');
  },
};

/**
 * List of all available categories
 */
export const availableCategories: string[] = [
  "CrUX",
  "Github: Actions",
  "Github: Branches",
  "Github: Dependabot",
  "Github: Discussions",
  "Github: Gists",
  "Github: Issues",
  "Github: Orgs",
  "Github: Projects",
  "Github: Pulls",
  "Github: Releases",
  "Github: Repos",
  "Github: Search",
  "Github: Wiki",
  "Knowledge Graph",
  "NPM",
  "PostgreSQL",
  "Swagger",
  "Utility",
  "k6"
];

/**
 * Load tools for specific categories only.
 * This allows skipping heavy SDK imports for categories that are excluded in config.
 *
 * @param categories - Array of category names to load. If empty or undefined, loads all categories.
 * @param excludeCategories - Array of category names to exclude from loading.
 */
export async function loadToolsByCategories(
  categories?: string[],
  excludeCategories?: string[]
): Promise<void> {
  // Expand parent category prefixes (e.g., "Github" -> "Github: Actions", "Github: Branches", etc.)
  const expandParentCategories = (cats: string[]): string[] => {
    const expanded: string[] = [];
    for (const cat of cats) {
      if (availableCategories.includes(cat)) {
        expanded.push(cat);
      } else {
        // Check if it's a parent prefix (e.g., "Github" matches "Github: Actions")
        const children = availableCategories.filter(c => c.startsWith(cat + ': '));
        if (children.length > 0) {
          expanded.push(...children);
        } else {
          expanded.push(cat); // Keep unknown categories so the warning below catches them
        }
      }
    }
    return expanded;
  };

  const expandedCategories = categories && categories.length > 0
    ? expandParentCategories(categories)
    : undefined;

  const expandedExclude = excludeCategories && excludeCategories.length > 0
    ? expandParentCategories(excludeCategories)
    : excludeCategories;

  // Warn about unknown categories
  if (expandedCategories && expandedCategories.length > 0) {
    const unknownCategories = expandedCategories.filter(c => !availableCategories.includes(c));
    if (unknownCategories.length > 0) {
      logWarn(`[tool-loader] Unknown categories specified in includeCategories: ${unknownCategories.join(', ')}. Available categories: ${availableCategories.join(', ')}`);
    }
  }

  const categoriesToLoad = expandedCategories && expandedCategories.length > 0
    ? expandedCategories.filter(c => availableCategories.includes(c))
    : availableCategories;

  const excludeSet = new Set(expandedExclude || []);

  // Load categories concurrently using Promise.allSettled for resilience
  // If one category fails to load, others will still be available
  const categoriesToActuallyLoad = categoriesToLoad.filter(category => !excludeSet.has(category));

  const results = await Promise.allSettled(
    categoriesToActuallyLoad.map(async (category) => {
      const loader = categoryLoaders[category];
      if (loader) {
        await loader();
      }
      return category;
    })
  );

  // Log any failed category loads with category name for debugging
  for (let i = 0; i < results.length; i++) {
    const result = results[i];
    if (result.status === 'rejected') {
      logError(`[tool-loader] Failed to load category "${categoriesToActuallyLoad[i]}": ${result.reason}`);
    }
  }
}

/**
 * Load all tools (for backward compatibility).
 * Note: For better performance, prefer using loadToolsByCategories with specific categories.
 */
export async function loadAllTools(): Promise<void> {
  await loadToolsByCategories();
}
