#!/usr/bin/env bun
/**
 * collect-setup-docs.ts - Collect all SETUP.md files and embed them in the binary
 *
 * This script scans four locations for SETUP.md documentation:
 * 1. Native tools: src/tools/{tool-name}/SETUP.md
 * 2. Bundled MCPs: bundled/{mcp-name}/SETUP.md
 * 3. Remote MCPs: src/remote-mcps/SETUP_{mcp-id}.md
 * 4. Local MCPs: src/local-mcps/SETUP_{mcp-id}.md
 *
 * The collected documentation is embedded into a TypeScript module for production builds.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get directory paths
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

/**
 * Interface for a setup documentation entry
 */
export interface SetupDoc {
  toolId: string;
  content: string;
  source: 'native' | 'bundled' | 'remote' | 'local';
}

/**
 * Collect all SETUP.md files from native tools, bundled MCPs, remote MCPs, and local MCPs
 */
export function collectSetupDocs(): SetupDoc[] {
  const docs: SetupDoc[] = [];

  // Collect from native tools (src/tools/{tool-name}/SETUP.md)
  const nativeToolsDir = path.join(rootDir, 'src', 'tools');
  if (fs.existsSync(nativeToolsDir)) {
    const toolDirs = fs.readdirSync(nativeToolsDir, { withFileTypes: true });

    for (const dir of toolDirs) {
      if (dir.isDirectory()) {
        const setupPath = path.join(nativeToolsDir, dir.name, 'SETUP.md');
        if (fs.existsSync(setupPath)) {
          const content = fs.readFileSync(setupPath, 'utf-8');
          docs.push({
            toolId: dir.name,
            content,
            source: 'native'
          });
          console.log(`  ✓ Found native tool: ${dir.name}`);
        }
      }
    }
  }

  // Collect from bundled MCPs (bundled/{mcp-name}/SETUP.md)
  const bundledDir = path.join(rootDir, 'bundled');
  if (fs.existsSync(bundledDir)) {
    const mcpDirs = fs.readdirSync(bundledDir, { withFileTypes: true });

    for (const dir of mcpDirs) {
      if (dir.isDirectory()) {
        const setupPath = path.join(bundledDir, dir.name, 'SETUP.md');
        if (fs.existsSync(setupPath)) {
          const content = fs.readFileSync(setupPath, 'utf-8');
          docs.push({
            toolId: dir.name,
            content,
            source: 'bundled'
          });
          console.log(`  ✓ Found bundled MCP: ${dir.name}`);
        }
      }
    }
  }

  // Collect from remote MCPs (src/remote-mcps/SETUP_{mcp-id}.md)
  const remoteDir = path.join(rootDir, 'src', 'remote-mcps');
  if (fs.existsSync(remoteDir)) {
    const files = fs.readdirSync(remoteDir);

    for (const file of files) {
      if (file.startsWith('SETUP_') && file.endsWith('.md')) {
        // Extract tool ID from SETUP_{toolId}.md
        const toolId = file.substring(6, file.length - 3);
        const setupPath = path.join(remoteDir, file);
        const content = fs.readFileSync(setupPath, 'utf-8');
        docs.push({
          toolId,
          content,
          source: 'remote'
        });
        console.log(`  ✓ Found remote MCP: ${toolId}`);
      }
    }
  }

  // Collect from local MCPs (src/local-mcps/SETUP_{mcp-id}.md)
  const localDir = path.join(rootDir, 'src', 'local-mcps');
  if (fs.existsSync(localDir)) {
    const files = fs.readdirSync(localDir);

    for (const file of files) {
      if (file.startsWith('SETUP_') && file.endsWith('.md')) {
        // Extract tool ID from SETUP_{toolId}.md
        const toolId = file.substring(6, file.length - 3);
        const setupPath = path.join(localDir, file);
        const content = fs.readFileSync(setupPath, 'utf-8');
        docs.push({
          toolId,
          content,
          source: 'local'
        });
        console.log(`  ✓ Found local MCP: ${toolId}`);
      }
    }
  }

  return docs;
}

/**
 * Generate TypeScript module with embedded setup documentation
 */
export function generateSetupModule(docs: SetupDoc[]): string {
  // Escape backslashes and backticks in content for template literal
  const escapeForTemplate = (str: string): string => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$');
  };

  const entries = docs.map((doc) => {
    const escapedContent = escapeForTemplate(doc.content);
    return `  '${doc.toolId}:${doc.source}': {
    toolId: '${doc.toolId}',
    content: \`${escapedContent}\`,
    source: '${doc.source}'
  }`;
  });

  const content = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/collect-setup-docs.ts
// Last generated: ${new Date().toISOString()}

/**
 * Interface for a setup documentation entry
 */
export interface SetupDoc {
  toolId: string;
  content: string;
  source: 'native' | 'bundled' | 'remote' | 'local';
}

/**
 * Embedded setup documentation for production builds
 * Key format: '{toolId}:{source}' (e.g., 'github:native', 'confluence:bundled')
 */
export const SETUP_DOCS: Record<string, SetupDoc> = {
${entries.join(',\n')}
};

/**
 * Get setup documentation by tool ID and source type
 */
export function getEmbeddedSetupDoc(
  toolId: string,
  source: 'native' | 'bundled' | 'remote' | 'local'
): SetupDoc | null {
  const key = \`\${toolId}:\${source}\`;
  return SETUP_DOCS[key] || null;
}

/**
 * Get all available setup documentation entries
 */
export function getAllEmbeddedSetupDocs(): SetupDoc[] {
  return Object.values(SETUP_DOCS);
}
`;

  return content;
}

/**
 * Main function - collect docs and generate module
 */
async function main() {
  console.log('📚 Collecting setup documentation...');

  const docs = collectSetupDocs();
  console.log(`\n✅ Found ${docs.length} setup documents`);

  console.log('\n📝 Generating TypeScript module...');
  const moduleContent = generateSetupModule(docs);

  const outputDir = path.join(rootDir, 'src', 'generated');
  const outputPath = path.join(outputDir, 'setup-docs.ts');

  // Create output directory if it doesn't exist
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
    console.log(`Created directory: ${outputDir}`);
  }

  // Write the generated module
  fs.writeFileSync(outputPath, moduleContent, 'utf-8');
  console.log(`✅ Generated setup docs module: ${outputPath}`);

  // Print summary by source
  const bySource = docs.reduce(
    (acc, doc) => {
      acc[doc.source] = (acc[doc.source] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  console.log('\n📊 Summary:');
  console.log(`  Native tools: ${bySource.native || 0}`);
  console.log(`  Bundled MCPs: ${bySource.bundled || 0}`);
  console.log(`  Remote MCPs: ${bySource.remote || 0}`);
  console.log(`  Local MCPs: ${bySource.local || 0}`);
}

// Run if executed directly
if (import.meta.main) {
  main();
}
