#!/usr/bin/env bun
/**
 * generate-tools-doc.ts — write TOOLS.md from the running server.
 *
 * TOOLS.md was written by hand and drifted within a day: it claimed 142 native tools and
 * listed none of the Microsoft 365 tools added since, while describing itself as
 * generated. A document that says what a bundle contains is worth having only if it
 * cannot quietly stop being true.
 *
 * The source is `list-tools --json` rather than the source tree, because bundled MCP
 * servers register at runtime and cannot be seen by reading files.
 *
 * Usage:
 *   bun run scripts/generate-tools-doc.ts            write TOOLS.md
 *   bun run scripts/generate-tools-doc.ts --check    fail if TOOLS.md is out of date
 */

import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface ToolEntry {
  name: string;
  id: string;
  description?: string;
  category?: string;
  provider?: string;
}

const ROOT = join(import.meta.dir, '..');
const DOC = join(ROOT, 'TOOLS.md');
const LIST_TIMEOUT_MS = 180_000;

/**
 * Ask the server for its tools.
 *
 * The server does not exit on stdin EOF, so it is killed once the JSON has arrived
 * rather than waited on — otherwise this hangs indefinitely.
 *
 * @returns Tools as reported by list-tools
 */
async function collectTools(): Promise<ToolEntry[]> {
  return new Promise((resolve, reject) => {
    const child = spawn('bun', ['run', 'src/mcp.ts', 'list-tools', '--json'], {
      cwd: ROOT,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let out = '';
    child.stdout.on('data', (chunk: Buffer) => (out += chunk.toString()));
    const timer = setTimeout(() => {
      child.kill();
      reject(new Error(`list-tools did not finish within ${LIST_TIMEOUT_MS / 1000}s`));
    }, LIST_TIMEOUT_MS);

    child.on('exit', () => {
      clearTimeout(timer);
      const start = out.indexOf('[');
      if (start < 0) {
        reject(new Error('list-tools produced no JSON array'));
        return;
      }
      try {
        resolve(JSON.parse(out.slice(start, out.lastIndexOf(']') + 1)) as ToolEntry[]);
      } catch (error) {
        reject(new Error(`could not parse list-tools output: ${String(error)}`));
      }
    });
  });
}

/**
 * Render the inventory.
 *
 * @param tools - Tools reported by the server
 * @returns Markdown for TOOLS.md
 */
function render(tools: ToolEntry[]): string {
  const byCategory = new Map<string, ToolEntry[]>();
  for (const tool of tools) {
    const key = tool.category ?? 'Uncategorised';
    if (!byCategory.has(key)) byCategory.set(key, []);
    byCategory.get(key)!.push(tool);
  }

  const lines: string[] = [
    '# Tool & Capability Inventory',
    '',
    '<!-- Generated by scripts/generate-tools-doc.ts. Do not edit by hand: run',
    '     `bun run generate:tools-doc`. An earlier hand-written version claimed a tool',
    '     count that was wrong within a day, which is worse than having no document. -->',
    '',
    `Tools reachable when every category is enabled: **${tools.length}**.`,
    '',
    'A given install shows fewer, because categories are opt-in at install time. What each',
    'install actually exposes is listed in the bundle manifest and by `qnsc-mcp list-tools`.',
    '',
    '| Category | Tools |',
    '|---|---|',
  ];

  const categories = [...byCategory.keys()].sort((a, b) => a.localeCompare(b));
  for (const category of categories) {
    lines.push(`| ${category} | ${byCategory.get(category)!.length} |`);
  }
  lines.push('');

  for (const category of categories) {
    lines.push(`## ${category}`, '');
    lines.push('| Tool | What it does |');
    lines.push('|---|---|');
    for (const tool of byCategory.get(category)!.sort((a, b) => a.name.localeCompare(b.name))) {
      // First sentence only: a full description runs to several lines and makes the
      // table unreadable, and the detail is in the tool schema anyway.
      const summary = (tool.description ?? '')
        .split('. ')[0]
        .replace(/\|/g, '\\|')
        .slice(0, 160);
      lines.push(`| \`${tool.name}\` | ${summary} |`);
    }
    lines.push('');
  }

  return `${lines.join('\n')}`;
}

const tools = await collectTools();
const rendered = render(tools);

if (process.argv.includes('--check')) {
  const current = existsSync(DOC) ? readFileSync(DOC, 'utf8') : '';
  if (current.trim() !== rendered.trim()) {
    console.error(
      '✖ TOOLS.md is out of date. Run `bun run generate:tools-doc` and commit the result.',
    );
    process.exit(1);
  }
  console.log(`✓ TOOLS.md matches the ${tools.length} tools the server reports`);
  process.exit(0);
}

writeFileSync(DOC, rendered);
console.log(`✓ Wrote TOOLS.md from ${tools.length} tools`);
